version: '3.9'
services:
  hue-notifier:
    network_mode: host
    build: .
    environment:
      PORT: ${PORT}
      HUE_USERNAME: ${HUE_USERNAME}
      HUE_GROUP_ID: ${HUE_GROUP_ID}

  grafana:
    image: grafana/grafana:latest
    network_mode: host
    volumes:
      - './grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml'
      - './grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml'
      - './grafana/notifiers.yaml:/etc/grafana/provisioning/notifiers/notifiers.yaml'
      - './grafana/dashboards:/usr/share/grafana/dashboards'
    environment:
      NOTIFIER_PORT: ${PORT}
